### ISSUE TITLE
Questoin about mask

### ISSUE THREAD

**Issue by pavelxx1** [Tengfei-Wang/Implicit-Internal-Video-Inpainting#1]
Hi, thx for repo!
Can you explain - must I make mask for each frame from video manually? or
maybe has any automation tool?
thx!

**Comment by Tengfei-Wang** [comment]
In case you use some public datasets, e.g. DAVIS, you can use our preprocess script to generate masks from their annotations. Otherwise, you need to annotate your own masks. Fortunately, it is not necessary to annotate all frames. We also provide the code for the mask prediction that can propagate the mask from few annotated frames to other frames automatically. This means you only need to annotate few frames manually (e.g., 1 frame in our example).  To annotate these frames, you can use photoshop or some segmentation tools, like https://github.com/isl-org/Intseg.

**Comment by pavelxx1** [comment]
thanks bro!
